services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=voom'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=mq'
    ports:
      - '5672:5672'
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'  
      - '8025:8025'   
